# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

build-master:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

build:
  stage: build
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build --pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG"
  except:
    - master

# deploy:
#   image: scp
#   stage: deploy
#   script:
#     - projectName=$APP_NAME-$CI_COMMIT_REF_SLUG
#     - ssh root@xxx.xxx.xxx.xxx bash -c "'cd /root && docker-compose pull $projectName && docker-compose up -d $projectName'"
#     - deleteImages=$(ssh root@xxx.xxx.xxx.xxx bash -c "'docker images -q -f dangling=true $CI_REGISTRY_IMAGE'")
#     - ssh root@xxx.xxx.xxx.xxx bash -c "'docker rmi $deleteImages'"
#   only:
#     - dev
